# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"


  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y unzip curl
    curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
    sudo apt-get install gettext libssl-dev libcurl4-openssl-dev zlib1g libicu-dev uuid-dev
    dnvm upgrade -r coreclr
  SHELL
end
